#+TITLE: ГРАФИЧЕСКОЕ ПРЕДСТАВЛЕНИЕ РЕЗУЛЬТАТОВ ВЫЧИСЛЕНИЙ ПРИ РЕШЕНИИ ЧИСЛЕННЫХ ЗАДАЧ
#+LANGUAGE: ru
#+AUTHOR: В.Д. Панков
#+OPTIONS: toc:nil
#+DEPARTMENT: КАФЕДРА №43
#+TEACHER: М.В. Величко
#+COURSE: Информатика
#+TYPE: ОТЧЕТ О ЛАБОРАТОРНОЙ РАБОТЕ №4


* Выполнение идивидуального задания 

Цель: Знакомство с графическими возможностями MATLAB, особенностями
форматирования графиков. Визуализация результатов
вычислений. Закрепление навыков по преобразованию типов данных,
организации программ-сценариев, подпрограмм и организации диалогов.

Написать программу, которая:
1. запросит у пользователя математическую функцию;
2. запросит интервал [a, b] для построения графика заданной
   пользователем
   функции и проверит введенные значения на корректность ввода;
3. рассчитает значение интеграла $\int\limits^x_a f(x) dx$, где f(x) –
   функция, введенная пользователем, a – нижняя граница интервала для
   построения графика,
   x – текущее значение аргумента, x \in [a, b].
   Интеграл рассчитать любым удобным методом;
4. выведет результаты расчетов в виде таблицы с дискретными данными с
   3 столбцами (аргумент, функция, интеграл).
   Для вывода таблицы использовать не более 15 строк, охватывающих
   весь промежуток [a, b] с одинаковым шагом;
5. выведет график функции, заданной пользователем, и ее интеграла.
   Графическое окно должно быть разбито на два подокна,
   расположенных горизонтально или вертикально в зависимости от номера
   варианта (см. табл.  3). В первом подокне должен быть выведен
   график
   функции, заданной пользователем, во втором – график ее
   интеграла. На графиках функции и ее интеграла указать маркерами
   точки, по которым строились графики, маркерами прорисовать не более
   15 точек. Количество
   точек для построения линий графиков должно быть подобрано
   самостоятельно для отображения «гладкой» (не ломанной) линии. Стили
   линий и маркеров, их цвет, толщина выбирается в соответствии с
   номером
   варианта (см. табл. 3). На графиках тонкими горизонтальными
   пунктирными линиями отметить максимальное и минимальное значение
   функции и ее интеграла. На графиках прорисовать сетку. Все графики
   и
   оси должны быть подписаны.

В ходе выполнения лабораторной работы использовался 4 вариант,
согласно номеру из журнала.

В таблице [[tablevar]] представлен данные для моего варианта.

#+NAME: tablevar
#+CAPTION: Значения для моего варианта
|---+----+---------+-----------------+-------+---------+---------+-----+-----------+---------+------|
|   |  4 | Вертик. | Штрихпунктирная | Точка | Голубой | Зеленый | 2,5 | Штриховая | Зеленый | 2,25 |
|   |    |         | линия           |       |         |         |     | линия     |         |      |
| / | <> | <>      | <>              | <>    | <>      | <>      | <>  | <>        | <>      | <>   |
|---+----+---------+-----------------+-------+---------+---------+-----+-----------+---------+------|


** Тестовые данные

Для тестирования программы я обозначу несколько тестовых
данных:


- Первые тестовые данные
  - Функция: $f(x) = x$
  - Тогда график функции будет прямой показанный на рисунке

    [[]]
  - Интегралом же данной функции будет: $\int f(x) dx =
    \frac{x^2}{2} + C$
    
    График первообразной представлен на рисунке .

    [[]]
  - Ограничения [-10, 10]
  - Тогда значение определённого интеграла в начальной и крайней точке
    будет вычислено по следующим формулам:

    - $\frac{ (-10)^2}{2} - \frac{(-10)^2}{2} = 0$

    - $\frac{ (10)^2}{2} - \frac{(-10)^2}{2} = 0$

  - Расчитаем также значение в нулевой точке

    - $0 - \frac{(-10)^2}{2} = -50$

- Вторые тестовые данные

  - Функция $f(x) = \cos x$

  - Тогда график функции будет прямой показанный на рисунке

    [[]]
  - Интегралом же данной функции будет: $\int f(x) dx =
    \sin x + C$

    График первообразной представлен на рисунке .

    [[]]
  - Ограничения [-5, 5]

  - Рассчитаем значения опр. интеграла в точках: [-1,0,1]:
    - $\sin(-1) - \sin(-5) \approx -1.80$

    - $\sin(0) - \sin(-5) \approx 0.96$

    - $\sin(1) - \sin(-5) \approx -0.12$



** Листинги основной программы и подпрограмм

Для ввода корректного числа была создана функция =inputNumber=.
Код данной функции представлен в листинге .

#+CAPTION: Функция inputNumber
#+INCLUDE: ./src/inputNumber.m src octave

Для ввода корректных ограничений для построения графика была написана
функция =inputLimits=, которая позволяла вводить первое число меньше
второго.

#+CAPTION: Функция inputLimits
#+INCLUDE: ./src/inputLimits.m src octave


Для ввода данных в виде таблицы была создана функция =printtable=,
которая выводила три столбца значений согласно заданию.






